[package]
name = "forester-search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.19.0"
tantivy = "0.21.1"
tempfile = "3.10.0"
